/*
PROGRAM FILE NAME	: SETUP.CPP
PROGRAM NAME   		: MAIN PROGRAM CODE
PROGRAM DISCRIPTION	: THIS FILE CONTENTS MAIN MODULE
PROGRAM AUTHOR 		: Ashwin M. Hegde
PROGRAM LICENSE		: General Public License
PROGRAM WEBSITE		: http://www.globalcodes.net
PROGRAM EMAIL		: webmaster@globalcodes.net
Copyright(C) 2010; Globalcodes.(R)
All Right Reserved.
*/

// BUILD-IN HEADER FILES.
#include <iostream.h>
#include <iomanip.h>
#include <conio.h>
#include <ctype.h>
#include <stdlib.h>
#include <string.h>
#include <graphics.h>
#include <dos.h>
#include <process.h>
#include <time.h>

// AUTHOR DEFINED HEADER FILES.
#include <ashwin/security.cpp>
#include <ashwin/design.cpp>
#include <ashwin/input.cpp>
#include <ashwin/output.cpp>
#include <ashwin/validate.cpp>
#include <ashwin/error.cpp>
#include <ashwin/license.cpp>

//MAIN PROGRAMS BEGINS
int main()
{
	clrscr();
	progressbar();
getch();
return 0;
}